### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by Evavic44** [ivybarley/100DaysChallenge#5]
Hey, @ivybarley I think adding a contributing guideline will help people know what and how they are supposed to contribute to this repository. You can check out the draft below. If you want, I can raise a PR or not, that's completely cool. 🙂

A few things the guidelines will contain.
- What kind of contribution the project is looking for
- How to contribute to the project effectively
- Some simple but not so strict rules to follow while contributing to this project.
- Commit tips and commit message conventions.

And room for any other thing you would like to be in the guideline. 

## ⚡GuideLines Draft
Here is the draft I have for now. 👇🏽

<div align="center">
<h1>Contributing Guidelines</h1>
<p>Thanks for your interest in contributing to this repository. Below are a list of guidelines you can follow to effectively contribute to it.</p>
</div>

## Steps to Contribute👩‍💻👨‍💻
Please make sure you follow this guideline so your contribution can be merged as quickly as possible

## Issues / Features 🌟

When contributing to this repository, if you notice any bugs, or issues or you have an idea/feature you would like to add to this project, please raise an issue first.

## Making Changes ♻️
When making changes, fixing an issue, or adding features to this project, please only add code that is related to the issue or feature you have been assigned to. For E.g If your feature is to add a button, your pull request should contain code that adds the button only.

- Don't make two different changes in one pull request. If you see another issue aside from the one you are working on. Raise a different PR for it. 🙏🏽

- And remember, the smaller the change, the faster for it to be reviewed and merged. 🙂

- Do not delete or modify someone else's code in this repository, unless stated otherwise.

- Give a meaningful name to whatever file or folder you are adding.

## Commits ✨
Write your commit message in the imperative: "Fix bug" and not "Fixed bug" or "Fixes bug." This convention matches up with commit messages generated by commands like git merge and git revert.

- Keep your commits short but descriptive.
- Do not end a commit message with a period.

## Resources 📖

If you are completely new to open source contribution and everything written here sounds confusing to you, I highly recommend you check out these resources. They will get you up to speed and you can come back to contribute your awesome ideas.
Videos

- How to contribute to open source
- How to keep your GitHub Fork in sync and up to date

## Need more help? 🤔

You can refer to the following articles on the basics of Git and Github and also contact me, in case you are stuck:

- Forking a Repo
- Cloning a Repo
- How to create a Pull Request
- Getting started with Git and GitHub
- Learn GitHub from Scratch

Thank you for reading and Happy Contributing. 🤩

**Comment by ivybarley** [comment]
@Evavic44, I love this. I think we can have a new README on how people can contribute. Please feel free to create a PR.

**Comment by Evavic44** [comment]
Doing that now. 😎
